# Site settings
title: Noah Povis
email: n.c.povis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "noah40povis.github.io" # the base hostname & protocol for your site

twitter_username: technotechkid
github_username: noah40povis

# Build settings
markdown: kramdown
